CREATE DATABASE [SOME_DATABASE_FOR_YOUR_APPLICATION]
GO

USE [SOME_DATABASE_FOR_YOUR_APPLICATION]
GO

CREATE TABLE [dbo].[SOME_TABLE](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[GENDER] [char](1) NOT NULL)
GO