FROM mcr.microsoft.com/mssql/server:2017-latest

LABEL VERSION="1.0"
LABEL AUTHOR="Rodrigo Riccitelli Vieira"
LABEL Purpose="Custom SQL 2017 Image with Wait Utility"

EXPOSE 1433

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait