FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim

LABEL VERSION="1.1"
LABEL AUTHOR="Rodrigo Riccitelli Vieira"
LABEL Purpose="Custom ASP .Net Core 3.1 SDK Image with Wait Utility"

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait